language: go
sudo: false
go: 1.11.x

os:
  - linux
  - osx
  - windows

env: GO111MODULE=on

# for some reason /usr/local is owned by a different user in travis, so we transfer ownership to the current user:
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo chown -R $(whoami) /usr/local; fi

branches:
  only:
  - develop
  - travis-testing

jobs:
  include:
  - stage: build
    name: build
    script:
      - make install
      - make build
  - stage: test
    name: lint
    install: true # this skips the installation step
    script: make lint
  - name: test
    script:
      - make genproto
      - make test
  - name: test-tidy
    script:
      - make genproto
      - make test-tidy

cache:
  directories:
    - $GOPATH/pkg/mod
